- name: Add nginx stable ppa
  become: true
  apt_repository: repo=ppa:nginx/stable state=present

- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install nginx
  become: true
  apt: name=nginx state=present
