---
- name: Add nginx stable ppa
  become: true
  apt_repository: repo=ppa:nginx/stable state=present

- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install nginx
  become: true
  apt: name=nginx state=present

- name: Add nginx.conf
  become: true
  template: src=nginx.tpl dest=/etc/nginx/nginx.conf
  notify: Restart nginx

- name: Change default nginx site
  become: true
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: Restart nginx
